ds:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: 123456

redis:
  host: 172.30.222.122

fdfs:
  ngix: http://10.103.15.180:8888
  tracker-list:
    - 10.103.15.180:22122
